#! /usr/bin/php
<?php
/**
 * ScanBackup
 *
 * @package PhotoSort
 */


//require_once 'profiling.php';

require_once 'src/utility/CLIScript.php';

class ScanBackup extends \PhotoSort\Utility\CLIScript {
  public function __construct() {
    $this->expectParam('path', self::PARAM_TYPE_STRING, self::PARAM_REQUIRED|self::PARAM_VALUE_REQUIRED);
    $this->expectParam('index', self::PARAM_TYPE_STRING, self::PARAM_OPTIONAL|self::PARAM_VALUE_REQUIRED);
  }

  public function main() {
    $aParams     = $this->getParams();
    $oPathParam  = $aParams['path'];
    $oIndexParam = $aParams['index'];
    $this->validatePath($oPathParam->mValue);
    $this->loadDependencies();

    $sBackupPath = $oPathParam->mValue;
    $sIndexPath  = $oIndexParam->bParamProvided ? $oIndexParam->mValue : 'data/archive.index';

    // Create the Visitor
    $oVisitor = new \PhotoSort\Scanner\Visitor(
      new \PhotoSort\Scanner\IndexedBackupScanner(
        new \PhotoSort\Archive\ImageMetaHasher(),
        $sIndexPath
      )
    );

    // Create the Scanner and Go!
    $oDirectoryScanner = new \PhotoSort\Scanner\RecursiveDirectoryScanner();
    $oDirectoryScanner
      ->addDirectoryExclusion(\PhotoSort\Scanner\IndexedBackupScanner::DUPEDIR_NAME)
      ->addDirectoryVisitor($oVisitor)
      ->addFileVisitor($oVisitor)
      ->scan($sBackupPath);
  }

  private function validatePath(string $sPath) {
    if (
      !file_exists($sPath) ||
      !is_dir($sPath) ||
      !is_readable($sPath)
    ) {
      throw new Exception("Unable to read $sPath for indexing");
    }
  }

  private function loadDependencies() {
    require_once 'src/archive/interfaces.php';
    require_once 'src/scanner/interfaces.php';
    require_once 'src/utility/interfaces.php';
    require_once 'src/archive/ImageMetaHasher.php';
    require_once 'src/scanner/Visitor.php';
    require_once 'src/scanner/RecursiveDirectoryScanner.php';
    require_once 'src/scanner/IndexedBackupScanner.php';
  }
}

try {
  $oScript = new ScanBackup();
  $oScript->main();
} catch (Exception $oErr) {
  echo $oErr->getMessage(), "\n";
}

exit();



