#! /usr/bin/php
<?php
/**
 * ScanBackup
 *
 * @package PhotoSort
 */

//require_once 'profiling.php';

require_once 'src/utility/CLIScript.php';

class TestScript extends \PhotoSort\Utility\CLIScript {

  public function __construct() {
    $this->expectParam('reqint', self::PARAM_TYPE_INTEGER, self::PARAM_REQUIRED|self::PARAM_VALUE_REQUIRED);
    $this->expectParam('optstr', self::PARAM_TYPE_STRING,  self::PARAM_OPTIONAL|self::PARAM_VALUE_OPTIONAL);
    $this->expectParam('optflt', self::PARAM_TYPE_FLOAT,   self::PARAM_OPTIONAL|self::PARAM_VALUE_REQUIRED);
    $this->expectParam('switch', self::PARAM_TYPE_SWITCH,  self::PARAM_OPTIONAL);
  }

  public function main() {
    var_dump($this->getParams());
  }
}

$oScript = new TestScript();
$oScript->main();
